// <auto-generated />
using System;
using HR_Management.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR_Management.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817222113_CompaniesAndDepartmentsTablesAdding")]
    partial class CompaniesAndDepartmentsTablesAdding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR_Management.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 4"
                        },
                        new
                        {
                            Id = 5,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 5"
                        },
                        new
                        {
                            Id = 6,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 6"
                        },
                        new
                        {
                            Id = 7,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 7"
                        },
                        new
                        {
                            Id = 8,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 8"
                        },
                        new
                        {
                            Id = 9,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 9"
                        },
                        new
                        {
                            Id = 10,
                            Address = "",
                            Industry = "Technology",
                            Name = "Technology Company 10"
                        },
                        new
                        {
                            Id = 11,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 1"
                        },
                        new
                        {
                            Id = 12,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 2"
                        },
                        new
                        {
                            Id = 13,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 3"
                        },
                        new
                        {
                            Id = 14,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 4"
                        },
                        new
                        {
                            Id = 15,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 5"
                        },
                        new
                        {
                            Id = 16,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 6"
                        },
                        new
                        {
                            Id = 17,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 7"
                        },
                        new
                        {
                            Id = 18,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 8"
                        },
                        new
                        {
                            Id = 19,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 9"
                        },
                        new
                        {
                            Id = 20,
                            Address = "",
                            Industry = "Pharmaceuticals",
                            Name = "Pharmaceuticals Company 10"
                        },
                        new
                        {
                            Id = 21,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 1"
                        },
                        new
                        {
                            Id = 22,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 2"
                        },
                        new
                        {
                            Id = 23,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 3"
                        },
                        new
                        {
                            Id = 24,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 4"
                        },
                        new
                        {
                            Id = 25,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 5"
                        },
                        new
                        {
                            Id = 26,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 6"
                        },
                        new
                        {
                            Id = 27,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 7"
                        },
                        new
                        {
                            Id = 28,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 8"
                        },
                        new
                        {
                            Id = 29,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 9"
                        },
                        new
                        {
                            Id = 30,
                            Address = "",
                            Industry = "Laboratory Equipment",
                            Name = "Laboratory Equipment Company 10"
                        },
                        new
                        {
                            Id = 31,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 1"
                        },
                        new
                        {
                            Id = 32,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 2"
                        },
                        new
                        {
                            Id = 33,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 3"
                        },
                        new
                        {
                            Id = 34,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 4"
                        },
                        new
                        {
                            Id = 35,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 5"
                        },
                        new
                        {
                            Id = 36,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 6"
                        },
                        new
                        {
                            Id = 37,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 7"
                        },
                        new
                        {
                            Id = 38,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 8"
                        },
                        new
                        {
                            Id = 39,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 9"
                        },
                        new
                        {
                            Id = 40,
                            Address = "",
                            Industry = "Real Estate",
                            Name = "Real Estate Company 10"
                        });
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(4968),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5023),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5026),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5032),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5035),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5047),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5059),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5062),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5064),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5071),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5080),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5083),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5088),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5091),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5102),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5126),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5130),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5134),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5139),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5141),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5143),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5148),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5155),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5158),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 25,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5163),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 26,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5165),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 27,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5170),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 28,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5175),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 29,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5178),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 30,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5184),
                            Description = "",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 31,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5215),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 32,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5219),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 33,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5221),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 34,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5228),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 35,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5231),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 36,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5233),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 37,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5238),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 38,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5240),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 39,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5243),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 40,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5248),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 41,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5250),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 42,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5253),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 43,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5258),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 44,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5260),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 45,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5263),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 46,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5268),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 47,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5270),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 48,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5273),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 49,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5278),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 50,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5281),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 51,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5283),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 52,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5288),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 53,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5290),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 54,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5294),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 55,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5299),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 56,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5302),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 57,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5304),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 58,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5309),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 59,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5312),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 60,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5314),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 61,
                            CompanyId = 21,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5319),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 62,
                            CompanyId = 21,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5322),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 63,
                            CompanyId = 21,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5325),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 64,
                            CompanyId = 22,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5330),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 65,
                            CompanyId = 22,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5332),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 66,
                            CompanyId = 22,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5336),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 67,
                            CompanyId = 23,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5341),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 68,
                            CompanyId = 23,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5344),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 69,
                            CompanyId = 23,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5346),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 70,
                            CompanyId = 24,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5351),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 71,
                            CompanyId = 24,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5354),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 72,
                            CompanyId = 24,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5357),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 73,
                            CompanyId = 25,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5369),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 74,
                            CompanyId = 25,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5372),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 75,
                            CompanyId = 25,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5374),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 76,
                            CompanyId = 26,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5382),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 77,
                            CompanyId = 26,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5385),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 78,
                            CompanyId = 26,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5387),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 79,
                            CompanyId = 27,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5392),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 80,
                            CompanyId = 27,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5395),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 81,
                            CompanyId = 27,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5397),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 82,
                            CompanyId = 28,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5402),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 83,
                            CompanyId = 28,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5405),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 84,
                            CompanyId = 28,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5407),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 85,
                            CompanyId = 29,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5412),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 86,
                            CompanyId = 29,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5415),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 87,
                            CompanyId = 29,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5417),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 88,
                            CompanyId = 30,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5422),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 89,
                            CompanyId = 30,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5425),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 90,
                            CompanyId = 30,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5427),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 91,
                            CompanyId = 31,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5432),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 92,
                            CompanyId = 31,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5435),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 93,
                            CompanyId = 31,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5437),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 94,
                            CompanyId = 32,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5442),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 95,
                            CompanyId = 32,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5445),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 96,
                            CompanyId = 32,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5447),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 97,
                            CompanyId = 33,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5452),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 98,
                            CompanyId = 33,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5455),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 99,
                            CompanyId = 33,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5457),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 100,
                            CompanyId = 34,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5462),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 101,
                            CompanyId = 34,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5465),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 102,
                            CompanyId = 34,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5467),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 103,
                            CompanyId = 35,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5472),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 104,
                            CompanyId = 35,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5475),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 105,
                            CompanyId = 35,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5478),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 106,
                            CompanyId = 36,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5482),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 107,
                            CompanyId = 36,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5485),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 108,
                            CompanyId = 36,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5488),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 109,
                            CompanyId = 37,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5493),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 110,
                            CompanyId = 37,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5495),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 111,
                            CompanyId = 37,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5498),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 112,
                            CompanyId = 38,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5503),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 113,
                            CompanyId = 38,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5505),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 114,
                            CompanyId = 38,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5508),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 115,
                            CompanyId = 39,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5513),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 116,
                            CompanyId = 39,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5515),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 117,
                            CompanyId = 39,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5518),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 118,
                            CompanyId = 40,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5523),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 119,
                            CompanyId = 40,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5525),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 120,
                            CompanyId = 40,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 21, 11, 817, DateTimeKind.Local).AddTicks(5528),
                            Description = "",
                            Name = "Industrial"
                        });
                });

            modelBuilder.Entity("HR_Management.Core.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("HR_Management.Core.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefrehTokenExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Department", b =>
                {
                    b.HasOne("HR_Management.Core.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
