// <auto-generated />
using System;
using HR_Management.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR_Management.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250821183028_AddEmployeeTableAndSeedData")]
    partial class AddEmployeeTableAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR_Management.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Silicon Ave, San Francisco, CA",
                            Industry = "Technology",
                            Name = "Tech Solutions Ltd"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Health St, Boston, MA",
                            Industry = "Pharmaceuticals",
                            Name = "PharmaLife Inc"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Lab Rd, Chicago, IL",
                            Industry = "Laboratory Equipment",
                            Name = "LabGear Corp"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Property Ln, New York, NY",
                            Industry = "Real Estate",
                            Name = "Real Estate Group"
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Eco Blvd, Seattle, WA",
                            Industry = "Technology",
                            Name = "GreenTech Solutions"
                        },
                        new
                        {
                            Id = 6,
                            Address = "303 Wellness St, Austin, TX",
                            Industry = "Pharmaceuticals",
                            Name = "MediCare Pharma"
                        },
                        new
                        {
                            Id = 7,
                            Address = "404 Science Pkwy, San Diego, CA",
                            Industry = "Laboratory Equipment",
                            Name = "LabTech Inc"
                        },
                        new
                        {
                            Id = 8,
                            Address = "505 City St, Miami, FL",
                            Industry = "Real Estate",
                            Name = "Urban Realty"
                        },
                        new
                        {
                            Id = 9,
                            Address = "606 Innovation Rd, Austin, TX",
                            Industry = "Technology",
                            Name = "NextGen Tech"
                        },
                        new
                        {
                            Id = 10,
                            Address = "707 Cure Ave, Chicago, IL",
                            Industry = "Pharmaceuticals",
                            Name = "HealthPlus Pharma"
                        },
                        new
                        {
                            Id = 11,
                            Address = "808 Lab St, Boston, MA",
                            Industry = "Laboratory Equipment",
                            Name = "BioLab Corp"
                        },
                        new
                        {
                            Id = 12,
                            Address = "909 Urban Ave, Los Angeles, CA",
                            Industry = "Real Estate",
                            Name = "Skyline Realty"
                        },
                        new
                        {
                            Id = 13,
                            Address = "111 Tech Blvd, San Jose, CA",
                            Industry = "Technology",
                            Name = "Innovatech Solutions"
                        },
                        new
                        {
                            Id = 14,
                            Address = "222 Care St, Houston, TX",
                            Industry = "Pharmaceuticals",
                            Name = "Wellness Pharma"
                        },
                        new
                        {
                            Id = 15,
                            Address = "333 Science Rd, Philadelphia, PA",
                            Industry = "Laboratory Equipment",
                            Name = "Precision Labs"
                        },
                        new
                        {
                            Id = 16,
                            Address = "444 Property Ln, Denver, CO",
                            Industry = "Real Estate",
                            Name = "Metro Realty"
                        },
                        new
                        {
                            Id = 17,
                            Address = "555 Innovation Dr, Austin, TX",
                            Industry = "Technology",
                            Name = "FutureTech Ltd"
                        },
                        new
                        {
                            Id = 18,
                            Address = "666 Wellness Blvd, Miami, FL",
                            Industry = "Pharmaceuticals",
                            Name = "CureAll Pharma"
                        },
                        new
                        {
                            Id = 19,
                            Address = "777 Science Ave, Seattle, WA",
                            Industry = "Laboratory Equipment",
                            Name = "LabWorks Inc"
                        },
                        new
                        {
                            Id = 20,
                            Address = "888 Urban St, New York, NY",
                            Industry = "Real Estate",
                            Name = "Prime Realty"
                        });
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9082),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9170),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9183),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9205),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9214),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9250),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9277),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9286),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9295),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9314),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9336),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9345),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9361),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9370),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9379),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9437),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9446),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9459),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9478),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9485),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9492),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9509),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9526),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9535),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 25,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9551),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 26,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9561),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 27,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9574),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 28,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9593),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 29,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9603),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 30,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9617),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 31,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9707),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 32,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9721),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 33,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9730),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 34,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9749),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 35,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9758),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 36,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9767),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 37,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9783),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 38,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9790),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 39,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9799),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 40,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9814),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 41,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9827),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 42,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9835),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 43,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9850),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 44,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9856),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 45,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9863),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 46,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9878),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 47,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9887),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 48,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9897),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 49,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9912),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 50,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9922),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 51,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9928),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 52,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9945),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 53,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9954),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 54,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9963),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 55,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9978),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 56,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9987),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 57,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 307, DateTimeKind.Local).AddTicks(9995),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 58,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 308, DateTimeKind.Local).AddTicks(12),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 59,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 308, DateTimeKind.Local).AddTicks(21),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 60,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 21, 21, 30, 26, 308, DateTimeKind.Local).AddTicks(30),
                            Description = "",
                            Name = "Industrial"
                        });
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Castle Rd",
                            DateOfBirth = new DateTime(1996, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "ahmed.ali@example.com",
                            FullName = "Ahmed Ali",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 15000m,
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pear St",
                            DateOfBirth = new DateTime(1997, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "mona.hassan@example.com",
                            FullName = "Mona Hassan",
                            HireDate = new DateTime(2018, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 18000m,
                            Title = "HR Manager"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cedar St",
                            DateOfBirth = new DateTime(1998, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "omar.khaled@example.com",
                            FullName = "Omar Khaled",
                            HireDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 14000m,
                            Title = "Frontend Developer"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Castle Rd",
                            DateOfBirth = new DateTime(1991, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "sara.ibrahim@example.com",
                            FullName = "Sara Ibrahim",
                            HireDate = new DateTime(2019, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 15500m,
                            Title = "Backend Developer"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Castle Rd",
                            DateOfBirth = new DateTime(1992, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "youssef.mohamed@example.com",
                            FullName = "Youssef Mohamed",
                            HireDate = new DateTime(2016, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 22000m,
                            Title = "Team Lead"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Birch St",
                            DateOfBirth = new DateTime(1988, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "nadia.fathy@example.com",
                            FullName = "Nadia Fathy",
                            HireDate = new DateTime(2021, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 12000m,
                            Title = "Recruiter"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Peach St",
                            DateOfBirth = new DateTime(1989, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 6,
                            Email = "karim.adel@example.com",
                            FullName = "Karim Adel",
                            HireDate = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 13500m,
                            Title = "QA Engineer"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Castle Rd",
                            DateOfBirth = new DateTime(1987, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 7,
                            Email = "laila.samir@example.com",
                            FullName = "Laila Samir",
                            HireDate = new DateTime(2019, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 16000m,
                            Title = "UI/UX Designer"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Plum St",
                            DateOfBirth = new DateTime(1995, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 8,
                            Email = "hossam.ezzat@example.com",
                            FullName = "Hossam Ezzat",
                            HireDate = new DateTime(2015, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 25000m,
                            Title = "Project Manager"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Berry St",
                            DateOfBirth = new DateTime(1994, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 9,
                            Email = "mai.tarek@example.com",
                            FullName = "Mai Tarek",
                            HireDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 5000m,
                            Title = "Intern"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Stone Rd",
                            DateOfBirth = new DateTime(1999, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 10,
                            Email = "adel.magdy@example.com",
                            FullName = "Adel Magdy",
                            HireDate = new DateTime(2019, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 14500m,
                            Title = "System Administrator"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Bridge Rd",
                            DateOfBirth = new DateTime(1996, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 11,
                            Email = "nourhan.ahmed@example.com",
                            FullName = "Nourhan Ahmed",
                            HireDate = new DateTime(2020, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 13000m,
                            Title = "Marketing Specialist"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Tower St",
                            DateOfBirth = new DateTime(1991, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 12,
                            Email = "mohamed.reda@example.com",
                            FullName = "Mohamed Reda",
                            HireDate = new DateTime(2017, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 20000m,
                            Title = "Senior Developer"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Castle Rd",
                            DateOfBirth = new DateTime(1993, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 13,
                            Email = "aya.gamal@example.com",
                            FullName = "Aya Gamal",
                            HireDate = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 11000m,
                            Title = "Content Writer"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Castle Rd",
                            DateOfBirth = new DateTime(1998, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 14,
                            Email = "tamer.saad@example.com",
                            FullName = "Tamer Saad",
                            HireDate = new DateTime(2014, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "011111111111",
                            Salary = 24000m,
                            Title = "Finance Manager"
                        });
                });

            modelBuilder.Entity("HR_Management.Core.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("HR_Management.Core.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefrehTokenExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Department", b =>
                {
                    b.HasOne("HR_Management.Core.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Employee", b =>
                {
                    b.HasOne("HR_Management.Core.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
