// <auto-generated />
using System;
using HR_Management.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR_Management.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817224949_CompaniesAndDepartmentsTables")]
    partial class CompaniesAndDepartmentsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR_Management.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Silicon Ave, San Francisco, CA",
                            Industry = "Technology",
                            Name = "Tech Solutions Ltd"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Health St, Boston, MA",
                            Industry = "Pharmaceuticals",
                            Name = "PharmaLife Inc"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Lab Rd, Chicago, IL",
                            Industry = "Laboratory Equipment",
                            Name = "LabGear Corp"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Property Ln, New York, NY",
                            Industry = "Real Estate",
                            Name = "Real Estate Group"
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Eco Blvd, Seattle, WA",
                            Industry = "Technology",
                            Name = "GreenTech Solutions"
                        },
                        new
                        {
                            Id = 6,
                            Address = "303 Wellness St, Austin, TX",
                            Industry = "Pharmaceuticals",
                            Name = "MediCare Pharma"
                        },
                        new
                        {
                            Id = 7,
                            Address = "404 Science Pkwy, San Diego, CA",
                            Industry = "Laboratory Equipment",
                            Name = "LabTech Inc"
                        },
                        new
                        {
                            Id = 8,
                            Address = "505 City St, Miami, FL",
                            Industry = "Real Estate",
                            Name = "Urban Realty"
                        },
                        new
                        {
                            Id = 9,
                            Address = "606 Innovation Rd, Austin, TX",
                            Industry = "Technology",
                            Name = "NextGen Tech"
                        },
                        new
                        {
                            Id = 10,
                            Address = "707 Cure Ave, Chicago, IL",
                            Industry = "Pharmaceuticals",
                            Name = "HealthPlus Pharma"
                        },
                        new
                        {
                            Id = 11,
                            Address = "808 Lab St, Boston, MA",
                            Industry = "Laboratory Equipment",
                            Name = "BioLab Corp"
                        },
                        new
                        {
                            Id = 12,
                            Address = "909 Urban Ave, Los Angeles, CA",
                            Industry = "Real Estate",
                            Name = "Skyline Realty"
                        },
                        new
                        {
                            Id = 13,
                            Address = "111 Tech Blvd, San Jose, CA",
                            Industry = "Technology",
                            Name = "Innovatech Solutions"
                        },
                        new
                        {
                            Id = 14,
                            Address = "222 Care St, Houston, TX",
                            Industry = "Pharmaceuticals",
                            Name = "Wellness Pharma"
                        },
                        new
                        {
                            Id = 15,
                            Address = "333 Science Rd, Philadelphia, PA",
                            Industry = "Laboratory Equipment",
                            Name = "Precision Labs"
                        },
                        new
                        {
                            Id = 16,
                            Address = "444 Property Ln, Denver, CO",
                            Industry = "Real Estate",
                            Name = "Metro Realty"
                        },
                        new
                        {
                            Id = 17,
                            Address = "555 Innovation Dr, Austin, TX",
                            Industry = "Technology",
                            Name = "FutureTech Ltd"
                        },
                        new
                        {
                            Id = 18,
                            Address = "666 Wellness Blvd, Miami, FL",
                            Industry = "Pharmaceuticals",
                            Name = "CureAll Pharma"
                        },
                        new
                        {
                            Id = 19,
                            Address = "777 Science Ave, Seattle, WA",
                            Industry = "Laboratory Equipment",
                            Name = "LabWorks Inc"
                        },
                        new
                        {
                            Id = 20,
                            Address = "888 Urban St, New York, NY",
                            Industry = "Real Estate",
                            Name = "Prime Realty"
                        });
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6263),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6345),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6351),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6365),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6370),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6398),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6414),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6419),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6423),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6434),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6442),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6447),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6455),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6459),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6463),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6500),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6526),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 6,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6546),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6579),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6596),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 7,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6601),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6610),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6620),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 8,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6624),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 25,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6631),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 26,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6649),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 27,
                            CompanyId = 9,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6676),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 28,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6685),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 29,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6702),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 30,
                            CompanyId = 10,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6740),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 31,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6837),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 32,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6876),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 33,
                            CompanyId = 11,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6892),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 34,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(6966),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 35,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7007),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 36,
                            CompanyId = 12,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7025),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 37,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7051),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 38,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7087),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 39,
                            CompanyId = 13,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7097),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 40,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7115),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 41,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7120),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 42,
                            CompanyId = 14,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7123),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 43,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7131),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 44,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7135),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 45,
                            CompanyId = 15,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7139),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 46,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7147),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 47,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7150),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 48,
                            CompanyId = 16,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7154),
                            Description = "",
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 49,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7160),
                            Description = "",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 50,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7167),
                            Description = "",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 51,
                            CompanyId = 17,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7178),
                            Description = "",
                            Name = "AI Research"
                        },
                        new
                        {
                            Id = 52,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7186),
                            Description = "",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 53,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7189),
                            Description = "",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 54,
                            CompanyId = 18,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7194),
                            Description = "",
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = 55,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7201),
                            Description = "",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 56,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7205),
                            Description = "",
                            Name = "Testing Kits"
                        },
                        new
                        {
                            Id = 57,
                            CompanyId = 19,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7208),
                            Description = "",
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 58,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7216),
                            Description = "",
                            Name = "Residential"
                        },
                        new
                        {
                            Id = 59,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7221),
                            Description = "",
                            Name = "Commercial"
                        },
                        new
                        {
                            Id = 60,
                            CompanyId = 20,
                            CreatedAt = new DateTime(2025, 8, 18, 1, 49, 46, 943, DateTimeKind.Local).AddTicks(7224),
                            Description = "",
                            Name = "Industrial"
                        });
                });

            modelBuilder.Entity("HR_Management.Core.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("HR_Management.Core.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefrehTokenExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Department", b =>
                {
                    b.HasOne("HR_Management.Core.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HR_Management.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR_Management.Core.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
